// Decompiled with JetBrains decompiler
// Type: NexPlugin.DataStore
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0418E061-3ED1-4467-97F2-4F1CA34BFCD4
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\Wildfrost\Modded\Wildfrost_Data\Managed\Assembly-CSharp-Publicized.dll

using System;

#nullable disable
namespace NexPlugin
{
  public static class DataStore
  {
    public const ulong INVALID_DATAID = 0;
    public const ushort INVALID_DATA_TYPE = 65535;
    public const ulong INVALID_PASSWORD = 0;
    public const uint MAX_NAME_LENGTH = 64;
    public const uint MAX_SEARCH_RESULT_SIZE = 100;
    public const uint MAX_SEARCH_ANY_RESULT_SIZE = 20;
    public const uint MAX_SEARCH_DATA_TYPE_SIZE = 10;
    public const uint NUM_TAG_SLOT = 16;
    public const uint RATING_SLOT_MAX = 15;
    public const uint NUM_RATING_SLOT = 16;
    public const uint MAX_TAG_LENGTH = 24;
    public const ushort DEFAULT_PERIOD = 90;
    public const uint DEFAULT_HTTP_THREAD_PRIORITY = 16;
    public const uint DEFAULT_RELAY_BUFFER_SIZE = 16384;
    public const uint DEFAULT_HTTP_BUFFER_SIZE = 32768;
    public const uint DEFAULT_DATA_TRANSFER_TIMEOUT_BYTES_PER_SECOND = 167;
    public const int DEFAULT_DATA_TRANSFER_MINIMUM_TIMEOUT = 60000;
    public const uint DEFAULT_HTTP_SEND_SOCKET_BUFFER_SIZE = 65536;
    public const uint DEFAULT_HTTP_RECV_SOCKET_BUFFER_SIZE = 65536;
    public const ushort INVALID_PERSISTENCE_SLOT_ID = 65535;
    public const ushort NUM_PERSISTENCE_SLOT = 16;
    public const uint BATCH_PROCESSING_CAPACITY_POST_OBJECT = 16;
    public const uint BATCH_PROCESSING_CAPACITY = 100;
    public const ulong RESULTRANGE_ANY_OFFSET = 4294967295;
    public const uint RESULTRANGE_DEFAULT_SIZE = 20;

    public enum Permission
    {
      PERMISSION_PUBLIC,
      PERMISSION_FRIEND,
      PERMISSION_SPECIFIED,
      PERMISSION_PRIVATE,
      PERMISSION_SPECIFIED_FRIEND,
    }

    [Flags]
    public enum DataFlag
    {
      DATA_FLAG_NONE = 0,
      DATA_FLAG_NEED_REVIEW = 1,
      DATA_FLAG_PERIOD_FROM_LAST_REFERRED = 2,
      DATA_FLAG_USE_READ_LOCK = 4,
      DATA_FLAG_USE_NOTIFICATION_ON_POST = 8,
      DATA_FLAG_USE_NOTIFICATION_ON_UPDATE = 16, // 0x00000010
      DATA_FLAG_NOT_USE_FILESERVER = 32, // 0x00000020
      DATA_FLAG_NEED_COMPLETION = 64, // 0x00000040
    }

    [Flags]
    public enum ModificationFlag
    {
      MODIFICATION_FLAG_NONE = 0,
      MODIFICATION_FLAG_NAME = 1,
      MODIFICATION_FLAG_ACCESS_PERMISSION = 2,
      MODIFICATION_FLAG_UPDATE_PERMISSION = 4,
      MODIFICATION_FLAG_PERIOD = 8,
      MODIFICATION_FLAG_METABINARY = 16, // 0x00000010
      MODIFICATION_FLAG_TAGS = 32, // 0x00000020
      MODIFICATION_FLAG_UPDATED_TIME = 64, // 0x00000040
      MODIFICATION_FLAG_DATA_TYPE = 128, // 0x00000080
      MODIFICATION_FLAG_STATUS = 512, // 0x00000200
    }

    public enum DataStatus
    {
      DATA_STATUS_NONE = 0,
      DATA_STATUS_PENDING = 2,
      DATA_STATUS_REJECTED = 5,
    }

    [Flags]
    public enum ComparisonFlag
    {
      COMPARISON_FLAG_NONE = 0,
      COMPARISON_FLAG_NAME = 1,
      COMPARISON_FLAG_ACCESS_PERMISSION = 2,
      COMPARISON_FLAG_UPDATE_PERMISSION = 4,
      COMPARISON_FLAG_PERIOD = 8,
      COMPARISON_FLAG_METABINARY = 16, // 0x00000010
      COMPARISON_FLAG_TAGS = 32, // 0x00000020
      COMPARISON_FLAG_DATA_TYPE = 64, // 0x00000040
      COMPARISON_FLAG_STATUS = 256, // 0x00000100
      COMPARISON_FLAG_ALL = 65535, // 0x0000FFFF
    }

    public enum SearchType
    {
      SEARCH_TYPE_PUBLIC = 1,
      SEARCH_TYPE_SEND_FRIEND = 2,
      SEARCH_TYPE_SEND_SPECIFIED = 3,
      SEARCH_TYPE_SEND_SPECIFIED_FRIEND = 4,
      SEARCH_TYPE_SEND = 5,
      SEARCH_TYPE_FRIEND = 6,
      SEARCH_TYPE_RECEIVED_SPECIFIED = 7,
      SEARCH_TYPE_RECEIVED = 8,
      SEARCH_TYPE_PRIVATE = 9,
      SEARCH_TYPE_OWN = 10, // 0x0000000A
      SEARCH_TYPE_OWN_PENDING = 12, // 0x0000000C
      SEARCH_TYPE_OWN_REJECTED = 13, // 0x0000000D
      SEARCH_TYPE_OWN_ALL = 14, // 0x0000000E
    }

    public enum SearchTarget
    {
      SEARCH_TARGET_ANYBODY,
      SEARCH_TARGET_FRIEND,
    }

    public enum SearchSortColumn
    {
      SEARCH_SORT_COLUMN_DATAID = 0,
      SEARCH_SORT_COLUMN_CREATED_TIME = 5,
      SEARCH_SORT_COLUMN_UPDATED_TIME = 6,
      SEARCH_SORT_COLUMN_RATING0 = 64, // 0x00000040
      SEARCH_SORT_COLUMN_RATING1 = 65, // 0x00000041
      SEARCH_SORT_COLUMN_RATING2 = 66, // 0x00000042
      SEARCH_SORT_COLUMN_RATING3 = 67, // 0x00000043
      SEARCH_SORT_COLUMN_RATING4 = 68, // 0x00000044
      SEARCH_SORT_COLUMN_RATING5 = 69, // 0x00000045
      SEARCH_SORT_COLUMN_RATING6 = 70, // 0x00000046
      SEARCH_SORT_COLUMN_RATING7 = 71, // 0x00000047
      SEARCH_SORT_COLUMN_RATING8 = 72, // 0x00000048
      SEARCH_SORT_COLUMN_RATING9 = 73, // 0x00000049
      SEARCH_SORT_COLUMN_RATING10 = 74, // 0x0000004A
      SEARCH_SORT_COLUMN_RATING11 = 75, // 0x0000004B
      SEARCH_SORT_COLUMN_RATING12 = 76, // 0x0000004C
      SEARCH_SORT_COLUMN_RATING13 = 77, // 0x0000004D
      SEARCH_SORT_COLUMN_RATING14 = 78, // 0x0000004E
      SEARCH_SORT_COLUMN_RATING15 = 79, // 0x0000004F
      SEARCH_SORT_COLUMN_RATING_AVERAGE0 = 96, // 0x00000060
      SEARCH_SORT_COLUMN_RATING_AVERAGE1 = 97, // 0x00000061
      SEARCH_SORT_COLUMN_RATING_AVERAGE2 = 98, // 0x00000062
      SEARCH_SORT_COLUMN_RATING_AVERAGE3 = 99, // 0x00000063
      SEARCH_SORT_COLUMN_RATING_AVERAGE4 = 100, // 0x00000064
      SEARCH_SORT_COLUMN_RATING_AVERAGE5 = 101, // 0x00000065
      SEARCH_SORT_COLUMN_RATING_AVERAGE6 = 102, // 0x00000066
      SEARCH_SORT_COLUMN_RATING_AVERAGE7 = 103, // 0x00000067
      SEARCH_SORT_COLUMN_RATING_AVERAGE8 = 104, // 0x00000068
      SEARCH_SORT_COLUMN_RATING_AVERAGE9 = 105, // 0x00000069
      SEARCH_SORT_COLUMN_RATING_AVERAGE10 = 106, // 0x0000006A
      SEARCH_SORT_COLUMN_RATING_AVERAGE11 = 107, // 0x0000006B
      SEARCH_SORT_COLUMN_RATING_AVERAGE12 = 108, // 0x0000006C
      SEARCH_SORT_COLUMN_RATING_AVERAGE13 = 109, // 0x0000006D
      SEARCH_SORT_COLUMN_RATING_AVERAGE14 = 110, // 0x0000006E
      SEARCH_SORT_COLUMN_RATING_AVERAGE15 = 111, // 0x0000006F
    }

    public enum SearchSortOrder
    {
      SEARCH_SORT_ORDER_ASC,
      SEARCH_SORT_ORDER_DESC,
    }

    [Flags]
    public enum ResultFlag
    {
      RESULT_FLAG_TAGS = 1,
      RESULT_FLAG_RATINGS = 2,
      RESULT_FLAG_METABINARY = 4,
      RESULT_FLAG_PERMITTED_IDS = 8,
    }

    public enum RatingLockType
    {
      RATING_LOCK_NONE,
      RATING_LOCK_INTERVAL,
      RATING_LOCK_PERIOD,
      RATING_LOCK_PERMANENT,
    }

    public enum RatingFlag
    {
      RATING_FLAG_MODIFIABLE = 4,
      RATING_FLAG_ROUND_MINUS = 8,
      RATING_FLAG_DISABLE_SELF_RATING = 16, // 0x00000010
    }

    [Flags]
    public enum RatingInternalFlag
    {
      RATING_INTERNAL_FLAG_USE_RANGE_MIN = 2,
      RATING_INTERNAL_FLAG_USE_RANGE_MAX = 4,
    }

    public enum RatingLockPeriod
    {
      RATING_LOCK_PERIOD_DAY1 = -17, // 0xFFFFFFEF
      RATING_LOCK_PERIOD_SUN = -7, // 0xFFFFFFF9
      RATING_LOCK_PERIOD_SAT = -6, // 0xFFFFFFFA
      RATING_LOCK_PERIOD_FRI = -5, // 0xFFFFFFFB
      RATING_LOCK_PERIOD_THU = -4, // 0xFFFFFFFC
      RATING_LOCK_PERIOD_WED = -3, // 0xFFFFFFFD
      RATING_LOCK_PERIOD_TUE = -2, // 0xFFFFFFFE
      RATING_LOCK_PERIOD_MON = -1, // 0xFFFFFFFF
    }

    public enum SearchResultTotalCountType
    {
      SEARCH_RESULT_TOTAL_EXACT,
      SEARCH_RESULT_TOTAL_MINIMUM,
      SEARCH_RESULT_TOTAL_ESTIMATE,
      SEARCH_RESULT_TOTAL_DISABLED,
    }
  }
}
